name: Build and Test React

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14']
    name: Node.js ${{ matrix.node }} build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ martix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-versions: ${{ matrix.node-version }}
      - name: Install dependecies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
